#!/usr/bin/env python3
"""Regenerate /Users/bytedance/Documents/AI_News/README.md with a chronological
index of all dated digest folders.

Run as part of the /ai-news skill after the compiler finishes, before git push.
Idempotent: rebuilds README.md from scratch each time based on what's on disk.
"""
import re
from pathlib import Path

ROOT = Path("/Users/bytedance/Documents/AI_News")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
HEAD_RE = re.compile(r"^#{1,3}\s+")
TLDR_RE = re.compile(r"^#{1,3}\s.*(at a glance|tl;?dr).*$", re.IGNORECASE)
MAX_BULLET_CHARS = 120


def first_bullets(path: Path, n: int) -> list[str]:
    if not path.exists():
        return []
    text = path.read_text()
    bullets: list[str] = []
    in_section = False
    for line in text.splitlines():
        if TLDR_RE.match(line):
            in_section = True
            continue
        if in_section and HEAD_RE.match(line):
            break
        if in_section and line.lstrip().startswith("- "):
            bullets.append(line.lstrip()[2:].strip())
            if len(bullets) >= n:
                return bullets
    if bullets:
        return bullets
    for line in text.splitlines():
        if line.lstrip().startswith("- "):
            bullets.append(line.lstrip()[2:].strip())
            if len(bullets) >= n:
                break
    return bullets


def shorten(s: str, max_len: int = MAX_BULLET_CHARS) -> str:
    s = re.sub(r"\*\*", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    if len(s) > max_len:
        s = s[: max_len - 1].rstrip() + "…"
    return s


def summary_for(date: str) -> str:
    ddir = ROOT / date
    bullets = first_bullets(ddir / "at-a-glance.md", n=2) or first_bullets(
        ddir / "index.md", n=2
    )
    if not bullets:
        return ""
    return " · ".join(shorten(b, 90) for b in bullets[:2])


def main() -> None:
    dates = sorted(
        [p.name for p in ROOT.iterdir() if p.is_dir() and DATE_RE.match(p.name)],
        reverse=True,
    )

    out: list[str] = [
        "# AI News Daily Digest",
        "",
        "Auto-compiled daily AI / ML / Agentic-engineering news digests, generated by a local OMAR agent fleet every weekday at 12:00 PT.",
        "",
        "Each digest contains:",
        "- A 10–14 bullet **At a Glance (TL;DR)**",
        "- Deep dives across ML research, AI industry, agentic AI, and best models",
        "- 6–8 matplotlib charts of the day's top benchmark results",
        "",
    ]
    if dates:
        latest = dates[0]
        out += [
            f"## Latest: [{latest}](./{latest}/)",
            "",
        ]
        latest_bullets = first_bullets(ROOT / latest / "at-a-glance.md", n=4) or first_bullets(
            ROOT / latest / "index.md", n=4
        )
        for b in latest_bullets[:4]:
            out.append(f"- {shorten(b, MAX_BULLET_CHARS)}")
        out.append("")
        out.append(f"[Read the full {latest} digest →](./{latest}/index.md)")
        out.append("")

    out += ["---", "", "## Archive", ""]
    for d in dates:
        s = summary_for(d)
        line = f"- **[{d}](./{d}/)**"
        if s:
            line += f" — {s}"
        out.append(line)
    out.append("")
    out += [
        "---",
        "",
        "*Generated by [OMAR](https://github.com/) and the `/ai-news` skill. README rebuilt automatically each run.*",
        "",
    ]

    (ROOT / "README.md").write_text("\n".join(out))
    print(f"Regenerated README.md with {len(dates)} digest entries")


if __name__ == "__main__":
    main()
